### ISSUE TITLE
I cannot make 'POST' request to work

### ISSUE THREAD

**Issue by javac9** [code-not-found/json-api#1]
Hi,

I can't make the 'post' request to work, at least not for the **json-api-crnk-relationship** module.

This is what I am trying to send as json:
`{
	"data": {
		"id": "3",
		"type": "articles",
		"attributes": {
			"title": "Foo Title"
		}
	}
}`

but I'm getting this:
`{
    "timestamp": 1513630003035,
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/codenotfound/api/articles"
}`

**Comment by code-not-found** [comment]
Hi,

Did you set the Content-Type header to "application/vnd.api+json"?

http://jsonapi.org/format/#content-negotiation-clients

**Comment by javac9** [comment]
Not really, I was using Postman, but did change to JSON (application/json). Is this not enough? If so, is there a way I can make Postman's header to use "vnd.api+json"?

**Comment by javac9** [comment]
Hi, I was using Postman and thought I was enough to select JSON (application/json) and it would work.
I explored it more and found out I can adjust the headers that are being sent. I edited the content-type to "vnd.api+json" and it worked. Thanks for the suggestion!
